abstract: Class Field Accessor Generator
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
build_requires: 
  Test::Base: 0.50
distribution_type: module
generated_by: Module::Install version 0.54
license: perl
name: Class-Field
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.6.1
version: 0.12
